# Generated by Django 5.2.9 on 2026-01-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', '결제 대기'), ('pending_acceptance', '주문 접수 대기'), ('preparing', '조리중'), ('cancelled', '주문 취소'), ('rejected', '주문 거절'), ('in_transit', '배달중'), ('delivered', '배달 완료')], default='pending_payment', max_length=20),
        ),
    ]
